# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='odata',
            new_name='odate',
        ),
    ]
